### ISSUE TITLE
Problem with status logic

### ISSUE THREAD

**Issue by Szarlus** [vViktorPL/pr-assistant#1]
The status `Some new changes has been pushed since your last comments in this PR. How about taking a look again?` is also displayed, when other people comment or resolve previous comments in which I am not involved. In my opinion events that should trigger this status should be either new commits to the PR or comments in the threads I am involved in (either started it or commented in one).

**Comment by vViktorPL** [comment]
@Szarlus: preview of fix proposal has been deployed here: https://deploy-preview-2--pr-assistant.netlify.app/
